### ISSUE TITLE
Suggestion: Remove email from contact form

### ISSUE THREAD

**Issue by xzonix** [thedev-me/register#13]
Hello! A few days ago, in is-a.dev, a week ago, a lot of people started receiving phishing emails, and it was caused because on the JSON files, there was an email form to fill, and some guys scrapped all the emails from there. I think the email type can be replaced with Discord just to prevent phishing.

**Comment by YazeedT** [comment]
Thank you for your input. That's a great point. I'll make it so you can either leave an email or a discord user name.

**Comment by YazeedT** [comment]
This suggestion has been implemented. Thank you for your insight.
