### ISSUE TITLE
Wildcard Domains

### ISSUE THREAD

**Issue by UntoldGam** [thedev-me/register#34]
Do you guys support wildcards?
e.g. *.domain.thedev.me

and with NS records on the wildcard domain for easy adding of sub-sub-domains e.g. blog.domain.thedev.me

**Comment by YazeedT** [comment]
We don't support wildcards.

We support NS records which advertently support sub-subdomains.

**Comment by UntoldGam** [comment]
Oh, so if I setup NS records, I could then add sub-sub-domains?

**Comment by UntoldGam** [comment]
Would the NS records be done like so:
- Add to cloudflare <domain>.thedev.me
- register the domain here + put the NS records on a PR for the domain ive registered here
- wait for approval
- boom i have a sub-domain to add sub-sub domains to?

**Comment by YazeedT** [comment]
You're correct. We don't offer wildcards but you can have as many levels of subdomains as you want via NS records.

**Comment by UntoldGam** [comment]
Alright, thanks for the help!

**Comment by UntoldGam** [comment]
👋
