### ISSUE TITLE
How to a Domain as  a verified domain? (Verify your is-a.dev Domain with GitHub Pages)

### ISSUE THREAD

**Issue by hanzas09** [thedev-me/register#79]
I want to add a {name}.thedev.me to my GitHub profile like in https://is-a.dev/?

Here is how they do it:
https://is-a.dev/docs/github-pages-verification/

But i don't see a way to do that in this repository. Highly appreciate if you can add that feature too.
Thanks you.

![IMG_20241212_075845](https://github.com/user-attachments/assets/94c961a7-5e02-4204-807c-bc458154d133)

**Comment by YazeedT** [comment]
Only add an A record or CNAME record based on what you need. Follow the instructions [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#dns-records-for-your-custom-domain) to know what values you need to add. Delete all other record types you do not need.

**Comment by hanzas09** [comment]
> Only add an A record or CNAME record based on what you need. Follow the instructions [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#dns-records-for-your-custom-domain) to know what values you need to add. Delete all other record types you do not need.

Thank you for the information. I found a better solution, Which i can control all of my dns records through https://desec.io/ (as I think). 

I already updated the the required NS record for that on the pull request. Please merge the pull request. Thanks.
